disable_existing_loggers: false
filters:
  correlation_id:
    (): asgi_correlation_id.CorrelationIdFilter
    default_value: '-'
    uuid_length: 32
formatters:
  app:
    class: logging.Formatter
    format: '[%(asctime)s.%(msecs)03d] [%(levelname)7s] [%(correlation_id)s] [%(funcName)s - %(module)s:%(lineno)d] %(message)s'
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  app:
    class: logging.StreamHandler
    filters:
      - correlation_id
    formatter: app
loggers:
  "gunicorn.error":
    handlers:
      - app
  "":
    handlers:
      - app
    level: INFO
    propagate: false


version: 1